export const books = [
    { name: 'Genesis', id: 'genesis', chapters: 50, abbreviations: ['Gen.', 'Gen', 'Ge', 'Gn', 'Genesis'] },
    { name: 'Exodus', id: 'exodus', chapters: 40, abbreviations: ['Ex.', 'Exod.', 'Exo.', 'Exo', 'Exodus'] },
    { name: 'Leviticus', id: 'leviticus', chapters: 27, abbreviations: ['Lev.', 'Le', 'Lv', 'Leviticus'] },
    { name: 'Numbers', id: 'numbers', chapters: 36, abbreviations: ['Num.', 'Nu', 'Nm', 'Nb', 'Numbers'] },
    { name: 'Deuteronomy', id: 'deuteronomy', chapters: 34, abbreviations: ['Deut.', 'De', 'Dt', 'Deuteronomy'] },
    { name: 'Joshua', id: 'joshua', chapters: 24, abbreviations: ['Josh.', 'Jos', 'Jsh', 'Joshua'] },
    { name: 'Judges', id: 'judges', chapters: 21, abbreviations: ['Judg.', 'Jdg', 'Jg', 'Jdgs', 'Judges'] },
    { name: 'Ruth', id: 'ruth', chapters: 4, abbreviations: ['Ruth', 'Rth.', 'Ru'] },
    { name: '1 Samuel', id: '1samuel', chapters: 31, abbreviations: ['1 Sam.', '1 Sm.', '1 Sa.', '1 S.', 'I Sam.', 'I Sa.', '1Sam.', '1Sa.', '1S.', '1st Samuel', '1st Sam.', 'First Samuel', 'First Sam.'] },
    { name: '2 Samuel', id: '2samuel', chapters: 24, abbreviations: ['2 Sam.', '2 Sm.', '2 Sa.', '2 S.', 'II Sam.', 'II Sa.', '2Sam.', '2Sa.', '2S.', '2nd Samuel', '2nd Sam.', 'Second Samuel', 'Second Sam.'] },
    { name: '1 Kings', id: '1kings', chapters: 22, abbreviations: ['1 Kings', '1 Kgs', '1 Ki', '1Kgs', '1Kin', '1Ki', '1K', 'I Kgs', 'I Ki', '1st Kings', '1st Kgs', 'First Kings', 'First Kgs'] },
    { name: '2 Kings', id: '2kings', chapters: 25, abbreviations: ['2 Kings', '2 Kgs', '2 Ki', '2Kgs', '2Kin', '2Ki', '2K', 'II Kgs', 'II Ki', '2nd Kings', '2nd Kgs', 'Second Kings', 'Second Kgs'] },
    { name: '1 Chronicles', id: '1chronicles', chapters: 29, abbreviations: ['1 Chron.', '1 Chr.', '1 Ch.', '1Chron.', '1Chr.', '1Ch.', 'I Chron.', 'I Chr.', 'I Ch.', '1st Chronicles', '1st Chron.', 'First Chronicles', 'First Chron.'] },
    { name: '2 Chronicles', id: '2chronicles', chapters: 36, abbreviations: ['2 Chron.', '2 Chr.', '2 Ch.', '2Chron.', '2Chr.', '2Ch.', 'II Chron.', 'II Chr.', 'II Ch.', '2nd Chronicles', '2nd Chron.', 'Second Chronicles', 'Second Chron.'] },
    { name: 'Ezra', id: 'ezra', chapters: 10, abbreviations: ['Ezra', 'Ezr.', 'Ez'] },
    { name: 'Nehemiah', id: 'nehemiah', chapters: 13, abbreviations: ['Neh.', 'Ne'] },
    { name: 'Esther', id: 'esther', chapters: 10, abbreviations: ['Est.', 'Esth.', 'Es'] },
    { name: 'Job', id: 'job', chapters: 42, abbreviations: ['Job', 'Jb'] },
    { name: 'Psalms', id: 'psalms', chapters: 150, abbreviations: ['Ps.', 'Psalm', 'Pslm.', 'Psa.', 'Psm.', 'Pss.', 'Psalms'] },
    { name: 'Proverbs', id: 'proverbs', chapters: 31, abbreviations: ['Prov', 'Pro.', 'Prv.', 'Pr', 'Proverbs'] },
    { name: 'Ecclesiastes', id: 'ecclesiastes', chapters: 12, abbreviations: ['Eccles.', 'Eccle.', 'Ecc.', 'Ec.', 'Qoh.', 'Ecclesiastes'] },
    { name: 'Song of Solomon', id: 'songofsolomon', chapters: 8, abbreviations: ['Song', 'Song of Songs', 'SOS.', 'So.', 'Canticle of Canticles', 'Canticles', 'Cant.', 'Song of Solomon'] },
    { name: 'Isaiah', id: 'isaiah', chapters: 66, abbreviations: ['Isa.', 'Is', 'Isaiah'] },
    { name: 'Jeremiah', id: 'jeremiah', chapters: 52, abbreviations: ['Jer.', 'Je', 'Jr', 'Jeremiah'] },
    { name: 'Lamentations', id: 'lamentations', chapters: 5, abbreviations: ['Lam.', 'La', 'Lamentations'] },
    { name: 'Ezekiel', id: 'ezekiel', chapters: 48, abbreviations: ['Ezek.', 'Eze', 'Ezk', 'Ezekiel'] },
    { name: 'Daniel', id: 'daniel', chapters: 12, abbreviations: ['Dan.', 'Da', 'Dn', 'Daniel'] },
    { name: 'Hosea', id: 'hosea', chapters: 14, abbreviations: ['Hos.', 'Ho', 'Hosea'] },
    { name: 'Joel', id: 'joel', chapters: 3, abbreviations: ['Joel', 'Jl'] },
    { name: 'Amos', id: 'amos', chapters: 9, abbreviations: ['Amos', 'Am'] },
    { name: 'Obadiah', id: 'obadiah', chapters: 1, abbreviations: ['Obad.', 'Ob', 'Obadiah'] },
    { name: 'Jonah', id: 'jonah', chapters: 4, abbreviations: ['Jonah', 'Jnh.', 'Jon.'] },
    { name: 'Micah', id: 'micah', chapters: 7, abbreviations: ['Mic.', 'Mc', 'Micah'] },
    { name: 'Nahum', id: 'nahum', chapters: 3, abbreviations: ['Nah.', 'Na', 'Nahum'] },
    { name: 'Habakkuk', id: 'habakkuk', chapters: 3, abbreviations: ['Hab.', 'Hb', 'Habakkuk'] },
    { name: 'Zephaniah', id: 'zephaniah', chapters: 3, abbreviations: ['Zeph.', 'Zep', 'Zp', 'Zephaniah'] },
    { name: 'Haggai', id: 'haggai', chapters: 2, abbreviations: ['Hag.', 'Hg', 'Haggai'] },
    { name: 'Zechariah', id: 'zechariah', chapters: 14, abbreviations: ['Zech.', 'Zec', 'Zc', 'Zechariah'] },
    { name: 'Malachi', id: 'malachi', chapters: 4, abbreviations: ['Mal.', 'Ml', 'Malachi'] },
    { name: 'Matthew', id: 'matthew', chapters: 28, abbreviations: ['Matt.', 'Mt', 'Matthew'] },
    { name: 'Mark', id: 'mark', chapters: 16, abbreviations: ['Mark', 'Mrk', 'Mar', 'Mk', 'Mr'] },
    { name: 'Luke', id: 'luke', chapters: 24, abbreviations: ['Luke', 'Luk', 'Lk'] },
    { name: 'John', id: 'john', chapters: 21, abbreviations: ['John', 'Joh', 'Jhn', 'Jn'] },
    { name: 'Acts', id: 'acts', chapters: 28, abbreviations: ['Acts', 'Act', 'Ac'] },
    { name: 'Romans', id: 'romans', chapters: 16, abbreviations: ['Rom.', 'Ro.', 'Rm.', 'Romans'] },
    { name: '1 Corinthians', id: '1corinthians', chapters: 16, abbreviations: ['1 Cor.', '1 Co.', 'I Cor.', 'I Co.', '1Cor.', '1Co.', 'I Corinthians', '1Corinthians', '1st Corinthians', 'First Corinthians'] },
    { name: '2 Corinthians', id: '2corinthians', chapters: 13, abbreviations: ['2 Cor.', '2 Co.', 'II Cor.', 'II Co.', '2Cor.', '2Co.', 'II Corinthians', '2Corinthians', '2nd Corinthians', 'Second Corinthians'] },
    { name: 'Galatians', id: 'galatians', chapters: 6, abbreviations: ['Gal.', 'Ga', 'Galatians'] },
    { name: 'Ephesians', id: 'ephesians', chapters: 6, abbreviations: ['Eph.', 'Ephes.', 'Ephesians'] },
    { name: 'Philippians', id: 'philippians', chapters: 4, abbreviations: ['Phil.', 'Php.', 'Pp', 'Philippians'] },
    { name: 'Colossians', id: 'colossians', chapters: 4, abbreviations: ['Col.', 'Co', 'Colossians'] },
    { name: '1 Thessalonians', id: '1thessalonians', chapters: 5, abbreviations: ['1 Thess.', '1 Thes.', '1 Th.', 'I Thessalonians', 'I Thess.', 'I Thes.', 'I Th.', '1Thessalonians', '1Thess.', '1Thes.', '1Th.', '1st Thessalonians', '1st Thess.', 'First Thessalonians', 'First Thess.'] },
    { name: '2 Thessalonians', id: '2thessalonians', chapters: 3, abbreviations: ['2 Thess.', '2 Thes.', '2 Th.', 'II Thessalonians', 'II Thess.', 'II Thes.', 'II Th.', '2Thessalonians', '2Thess.', '2Thes.', '2Th.', '2nd Thessalonians', '2nd Thess.', 'Second Thessalonians', 'Second Thess.'] },
    { name: '1 Timothy', id: '1timothy', chapters: 6, abbreviations: ['1 Tim.', '1 Ti.', 'I Timothy', 'I Tim.', 'I Ti.', '1Timothy', '1Tim.', '1Ti.', '1st Timothy', '1st Tim.', 'First Timothy', 'First Tim.'] },
    { name: '2 Timothy', id: '2timothy', chapters: 4, abbreviations: ['2 Tim.', '2 Ti.', 'II Timothy', 'II Tim.', 'II Ti.', '2Timothy', '2Tim.', '2Ti.', '2nd Timothy', '2nd Tim.', 'Second Timothy', 'Second Tim.'] },
    { name: 'Titus', id: 'titus', chapters: 3, abbreviations: ['Titus', 'Tit'] },
    { name: 'Philemon', id: 'philemon', chapters: 1, abbreviations: ['Philem.', 'Phm.', 'Pm.', 'Philemon'] },
    { name: 'Hebrews', id: 'hebrews', chapters: 13, abbreviations: ['Heb.', 'Hebrews'] },
    { name: 'James', id: 'james', chapters: 5, abbreviations: ['James', 'Jas', 'Jm', 'James'] },
    { name: '1 Peter', id: '1peter', chapters: 5, abbreviations: ['1 Pet.', '1 Pe.', '1 Pt.', '1 P.', 'I Pet.', 'I Pt.', 'I Pe.', '1Peter', '1Pet.', '1Pe.', '1Pt.', '1P.', 'I Peter', '1st Peter', 'First Peter'] },
    { name: '2 Peter', id: '2peter', chapters: 3, abbreviations: ['2 Pet.', '2 Pe.', '2 Pt.', '2 P.', 'II Pet.', 'II Pt.', 'II Pe.', '2Peter', '2Pet.', '2Pe.', '2Pt.', '2P.', '2nd Peter', 'Second Peter'] },
    { name: '1 John', id: '1john', chapters: 5, abbreviations: ['1 John', '1 Jhn.', '1 Jn.', '1 J.', '1John', '1Jhn.', '1Joh.', '1Jn.', '1Jo.', '1J.', 'I John', 'I Jhn.', 'I Joh.', 'I Jn.', 'I Jo.', '1st John', 'First John'] },
    { name: '2 John', id: '2john', chapters: 1, abbreviations: ['2 John', '2 Jhn.', '2 Jn.', '2 J.', '2John', '2Jhn.', '2Joh.', '2Jn.', '2Jo.', '2J.', 'II John', 'II Jhn.', 'II Joh.', 'II Jn.', 'II Jo.', '2nd John', 'Second John'] },
    { name: '3 John', id: '3john', chapters: 1, abbreviations: ['3 John', '3 Jhn.', '3 Jn.', '3 J.', '3John', '3Jhn.', '3Joh.', '3Jn.', '3Jo.', '3J.', 'III John', 'III Jhn.', 'III Joh.', 'III Jn.', 'III Jo.', '3rd John', 'Third John'] },
    { name: 'Jude', id: 'jude', chapters: 1, abbreviations: ['Jude', 'Jud.', 'Jd.'] },
    { name: 'Revelation', id: 'revelation', chapters: 22, abbreviations: ['Rev.', 'Re', 'Revelation'] },
  ];
  
  export const abbreviationsToFullName = {};
books.forEach(book => {
  book.abbreviations.forEach(abbreviation => {
    abbreviationsToFullName[abbreviation.toLowerCase()] = book.name;
  });
});